require 'tima.options'
require 'tima.keymaps'
require 'tima.plugins'
require 'tima.colorscheme'
require 'tima.statusline'
require 'tima.cmp'
require 'tima.lsp'
require 'tima.treesitter'
require 'tima.autopairs'
require 'tima.nvim_tree'
require 'tima.toggleterm'
require 'tima.autocommands'
require 'tima.rails_projections'

vim.cmd('let g:loaded_ruby_provider = 0')
